# This workflow will upload a Python Package using Twine when a release is created

name: Make Package # whenever you push to any branch you should run make package, but not the publish

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Package
        run: VERSION="${GITHUB_REF#refs/*/}" make package