# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package

on:
  push:
    tags:
      - '*'
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Clean
      run: rm -rf dist/ MANIFEST && git checkout smartystreets_python_sdk_version/__init__.py

    - name: Dependencies
      run: python3 -m pip install -r requirements.txt && python -m pip install --upgrade pip
        
    - name: Test
      run: python3 -m unittest discover -p *_test.py

    - name: Set Environment Variable
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Grab Version
      run: echo "__version__=\"${{ env.RELEASE_VERSION }}\"" >> smartystreets_python_sdk_version/__init__.py && python3 setup.py sdist && git checkout smartystreets_python_sdk_version/__init__.py

    - name: Publish package to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
